FROM python:3.11.1-slim-bullseye

ENV CLASSBOTEXTENDED \extendedBot

LABEL author=Igor<V0.1>

WORKDIR /extendedBot

COPY ClassBotExtended/. ./

#RUN apt-get update

#WORKDIR $EXTENDED_BOT

CMD ["python", "main.py"]