FROM python:3.11.1-slim-bullseye

#ENV CLASSBOTEXTENDED \extendedBot

LABEL author=Igor<V0.1>

WORKDIR /extendedBot

RUN apt-get update

#WORKDIR $EXTENDED_BOT

CMD ["echo", "Starting compilation of ExtendedBot..."]